"use client";
import { useState,type FormEvent } from 'react';
import { appPath } from '@/lib/app-path';

export default function LoginForm({setupRequired}:{setupRequired:boolean}){
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const response=await fetch(appPath(setupRequired?'/api/auth/setup':'/api/auth/login'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.trim(),email:email.trim(),password})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to continue.');window.location.assign(appPath('/'));}catch(error){setError(error instanceof Error?error.message:'Unable to continue.');}finally{setBusy(false);}}
 return <main className="login-page"><section className="login-story"><div className="login-brand"><span className="login-mark">c</span><strong>cove<span>.</span></strong></div><div className="login-story-copy"><span className="login-kicker">YOUR WORK, IN CALMER WATERS</span><h1>Make room for<br/><em>what matters.</em></h1><p>A private place for plans, projects, and the small steps that move everything forward.</p><div className="login-board-art"><div><span/><span/><span/></div><div><span/><span/></div><div><span/><span/><span/></div></div></div><small>Private by design · Thoughtfully organized</small></section><section className="login-panel"><form onSubmit={submit} autoComplete="on"><div className="login-heading"><span>{setupRequired?'FIRST THINGS FIRST':'WELCOME BACK'}</span><h2>{setupRequired?'Create your admin account':'Sign in to your space'}</h2><p>{setupRequired?'This first account owns account access and workspace permissions.':'Your boards are right where you left them.'}</p></div>{setupRequired&&<label>Your name<input autoFocus required maxLength={100} autoComplete="name" value={name} onChange={event=>setName(event.target.value)} placeholder="Your name"/></label>}<label>Email address<input autoFocus={!setupRequired} required type="email" inputMode="email" autoCapitalize="none" autoComplete="username" maxLength={255} value={email} onChange={event=>setEmail(event.target.value)} placeholder="you@example.com"/></label><label>Password<input required type="password" autoComplete={setupRequired?'new-password':'current-password'} minLength={setupRequired?12:1} maxLength={200} value={password} onChange={event=>setPassword(event.target.value)} placeholder={setupRequired?'At least 12 characters':'Your password'}/></label>{setupRequired&&<div className="password-note"><span>12+</span><p><strong>Use a long, unique password</strong><small>Password hashes are stored using scrypt. Your password is never saved in plain text.</small></p></div>}{error&&<div className="login-error" role="alert">{error}</div>}<button className="login-submit" disabled={busy}>{busy?'Securing your space…':setupRequired?'Create secure workspace':'Sign in'}<span>→</span></button><p className="login-security">Protected with secure, HTTP-only sessions and rate-limited sign-in.</p></form></section></main>;
}
