import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

async function main() {
  const temp=fs.mkdtempSync(path.join(os.tmpdir(),'trellis-data-test-'));
  process.env.DATA_DIR=temp;
  const {mutate,getState}=await import('../src/lib/store');
  const {sqlite}=await import('../src/db');
  const act=(action:string,payload:Record<string,unknown>={})=>mutate({action,...payload}) as Record<string,any>;
  try {
    const workspace=act('createWorkspace',{name:'Integration tests'}).id;
    const a=act('createBoard',{workspaceId:workspace,name:'A'}).id;
    const b=act('createBoard',{workspaceId:workspace,name:'B'}).id;
    const state=getState(),ca=state.columns.find(c=>c.boardId===a)!.id,cb=state.columns.find(c=>c.boardId===b)!.id;
    const c=act('createCard',{columnId:ca,title:'Shared card',description:'**Markdown**'});
    const tag=act('createTag',{workspaceId:workspace,name:'Test',color:'#ffddaa'}).id;
    act('toggleTag',{cardId:c.id,tagId:tag});
    let tray=act('addToTray',{placementId:c.placementId,mode:'link'}).id;
    assert.equal(getState().placements.find(p=>p.id===c.placementId)!.boardId,a,'Collecting preserves source');
    const linked=act('dropTray',{id:tray,columnId:cb,operationId:'link-once'});
    assert.equal(getState().placements.filter(p=>p.cardId===c.id).length,2);
    act('dropTray',{id:tray,columnId:cb,operationId:'link-once'});
    assert.equal(getState().placements.filter(p=>p.cardId===c.id).length,2,'Retries do not duplicate links');
    act('updateCard',{id:c.id,description:'Updated body'});
    assert.equal(getState().cards.find(x=>x.id===c.id)!.description,'Updated body');
    act('updateCard',{id:c.id,dueDate:'2026-09-24'});
    assert.equal(getState().cards.find(x=>x.id===c.id)!.dueDate,'2026-09-24','Calendar dates persist on the canonical card');
    act('updateCard',{id:c.id,scheduledStart:'2026-09-24T09:00:00.000Z',scheduledEnd:'2026-09-24T10:00:00.000Z'});
    assert.equal(getState().cards.find(x=>x.id===c.id)!.scheduledStart,'2026-09-24T09:00:00.000Z','Calendar hours persist on the canonical card');
    assert.throws(()=>act('updateCard',{id:c.id,scheduledStart:'2026-09-24T11:00:00.000Z',scheduledEnd:'2026-09-24T10:00:00.000Z'}),/after start/);
    assert.throws(()=>act('updateCard',{id:c.id,dueDate:'24/09/2026'}),/valid due date/);
    assert.equal(getState().cardTags.filter(x=>x.cardId===c.id).length,1);
    tray=act('addToTray',{placementId:c.placementId}).id;
    assert.throws(()=>act('dropTray',{id:tray,columnId:cb}),/already contains/);
    assert.ok(getState().tray.find(t=>t.id===tray),'Rejected drops keep tray');
    act('undo',{id:linked.undoId});
    assert.equal(getState().placements.filter(p=>p.cardId===c.id).length,1);
    assert.equal(getState().cards.find(x=>x.id===c.id)!.description,'Updated body','Undo preserves content edits');
    act('updateColumn',{id:cb,wipLimit:1,limitMode:'strict'});
    act('createCard',{columnId:cb,title:'Occupies last slot'});
    assert.throws(()=>act('dropTray',{id:tray,columnId:cb}),/reached its limit/);
    assert.equal(getState().placements.find(p=>p.id===c.placementId)!.boardId,a);
    assert.ok(getState().tray.find(t=>t.id===tray));
    act('updateColumn',{id:cb,limitMode:'warning'});
    const moved=act('dropTray',{id:tray,columnId:cb});
    assert.ok(moved.warning);
    assert.equal(getState().placements.find(p=>p.id===c.placementId)!.boardId,b);
    assert.equal(getState().tray.find(t=>t.id===tray),undefined);
    act('undo',{id:moved.undoId});
    assert.equal(getState().placements.find(p=>p.id===c.placementId)!.boardId,a);
    const other=act('createWorkspace',{name:'Other'}).id,otherBoard=act('createBoard',{workspaceId:other,name:'Other board'}).id;
    const otherColumn=getState().columns.find(x=>x.boardId===otherBoard)!.id;
    assert.throws(()=>act('movePlacement',{placementId:c.placementId,columnId:otherColumn}),/same workspace/);
    tray=act('addToTray',{placementId:c.placementId}).id;
    act('movePlacement',{placementId:c.placementId,columnId:ca,position:99});
    assert.throws(()=>act('dropTray',{id:tray,columnId:cb}),/moved after/);
    assert.throws(()=>act('removePlacement',{id:c.placementId}),/last board/);
    assert.throws(()=>act('addLink',{cardId:c.id,url:'javascript:alert(1)'}),/valid http/);
    const saved=getState().cards.find(x=>x.id===c.id)!;
    assert.throws(()=>act('updateCard',{id:c.id,title:'Stale',version:saved.version-1}),/changed/);
    assert.equal(sqlite.pragma('integrity_check',{simple:true}),'ok');
    sqlite.pragma('wal_checkpoint(TRUNCATE)');
    assert.ok(fs.statSync(path.join(temp,'trellis.sqlite')).size>0);
    console.log('PASS: persistence, calendar dates, links, shared content, tray safety, idempotent retry, WIP limits, undo, workspace boundaries, stale conflicts, URL validation, SQLite integrity.');
  } finally {sqlite.close();fs.rmSync(temp,{recursive:true,force:true});}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
